### ISSUE TITLE
asciidoc.report.rule.directory without asciidoc.report.file.include

### ISSUE THREAD

**Issue by dominikschlosser** [jqassistant-contrib/jqassistant-asciidoc-report-plugin#4]
If one specifies a rule-directory without specifying an include-file and the given directory contains other directories the build fails with following exception:

> com.buschmais.jqassistant:jqassistant-maven-plugin:1.6.0:analyze failed: (Errno::EACCES) 

The root of this problem are the following lines in AsciidocReportPlugin.java 163 ff.
```java
ruleDirectory.listFiles(new FilenameFilter() {
     @Override
     public boolean accept(File dir, String name) {
           return filePatternMatcher.accepts(name);
      }
 })
```

listFiles also returns directories. Using a FileFilter and checking for file.isFile() would fix this issue.

Adding unit tests for this seems to be non-trivial otherwise i would have submitted a PR

**Comment by DirkMahler** [comment]
The issue should be fixed now, the filter is now moved out to a separate class that is unit testable. Will provide a test in a second commit.

**Comment by DirkMahler** [comment]
Can you verify if the fix solves your problem with the current snapshot?

**Comment by dominikschlosser** [comment]
Works like a charm!
