### ISSUE TITLE
Import of existing concepts and constraints into specific asciidoc

### ISSUE THREAD

**Issue by StephanPirnbaum** [jqassistant-contrib/jqassistant-asciidoc-report-plugin#7]
When documenting design decisions and structures, the use case can occur that already written down concepts or constraints (e.g. coming from the spring or ddd plugin) shall be referenced including the rendering of the query and results. 

For that, I propose to implement an include-mechanism based on the id of a concept/constraint, e.g.

include::jQA:Rule[id="java-ddd:IllegalDependenciesBetweenBoundedContexts"]

**Comment by DirkMahler** [comment]
Done for 1.8.0
